"""empty message

Revision ID: 89e800c959df
Revises: 9adbc475055b
Create Date: 2021-08-25 16:40:23.834497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e800c959df'
down_revision = '9adbc475055b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isdelete', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('rdate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rdate')
    op.drop_column('user', 'isdelete')
    # ### end Alembic commands ###
